### ISSUE TITLE
make streamable

### ISSUE THREAD

**Issue by wanderer** [ethereumjs/rlp#1]
its possible. we should do it

**Comment by kumavis** [comment]
@wanderer do we have any streaming rlp data sources atm?

**Comment by wanderer** [comment]
@kumavis  yeah, networking stuff.

**Comment by wanderer** [comment]
also the format that i would image in streaming module would be something like this
`[ 1, 2, 3, [ 'test' ] ]`

which would get streamed
OPEN
1
2
3
OPEN
"test"
CLOSE
CLOSE

**Comment by holgerd77** [comment]
No discussion and no request from community to implement this for 2+ years, will close.
