### ISSUE TITLE
Consider having TypeScript/Flow interface definition

### ISSUE THREAD

**Issue by vietlq** [ethereumjs/rlp#24]
Do you have any plan to have TypeScript/Flow interface definition added? There are a few benefits:

* That would help a lot to improve safety
* Enable intellisense for RLP using VS Code
* Convert to BuckleScript/ReasonML ( https://rrdelaney.github.io/ReasonablyTyped/ )

**Comment by changtimwu** [comment]
I'm using this.  https://github.com/machinomy/types-rlp

**Comment by holgerd77** [comment]
I opened an issue over on the library if it would be possible to include this here (see link above).

**Comment by ukstv** [comment]
@holgerd77 As `safe-buffer` now contains TypeScript declarations, https://github.com/ethereumjs/rlp/pull/25 pull request can be used to include the declarations for `rlp` with no additional dependencies.

**Comment by holgerd77** [comment]
Hi Sergey, cool, thanks for following up, sorry, lost a bit track on this.

To be honest, I am still a bit lost. How can I test this? I tried to open the PR code in Visual Studio Code and hovering over the code in ``index.js``, but don't see proper type declarations, just e.g. ``(parameter) input:any`` when hovering over ``exports.encode``.

Do I miss something here?

**Comment by ukstv** [comment]
TS declarations have no effect on JS code. I would suggest creating a separate TS project, that links to `rlp` package. Inside that code you would see the difference.

**Comment by holgerd77** [comment]
Ah, thanks.

Is there any way to directly test from Node, npm, JS testing tool that the TS definitions match the underlaying JS code? Especially since library maintainer are no TS experts I would see this as problematic otherwise to keep this up-to-date.

**Comment by ukstv** [comment]
1. One could manually check the definitions against JSDoc.
1. One could create a TS project, add some dummy TS tests just to check if everything compiles, and put that into Travis.
1. One could translate existing test suite into TS and put it into that package above.
1. Rely on the users' feedback. If there is any discrepancy between TS and JS code, sooner or later you will know about that. In a good case, news like that are accompanied with a pull request.

**Comment by axic** [comment]
I agree with @holgerd77 that it would be nice having direct testing of the declaration. I like your idea of `One could translate existing test suite into TS and put it into that package above.` the most as that would mean we actually keep the definitions up to date.

In this single case however I would be happy to make an exception, given `rlp`s interface is so simple, I think we can maintain the definition.

**Comment by krzkaczor** [comment]
This is fixed by: https://github.com/ethereumjs/rlp/releases/tag/v2.2.0
