### ISSUE TITLE
Should rlp support bigint or mediumint in ethereum/tests?

### ISSUE THREAD

**Issue by sc0Vu** [ethereumjs/rlp#26]
Recently I run ethereal/tests/RLPtests with this library, the encoded [medium int](https://github.com/ethereum/tests/blob/develop/RLPTests/rlptest.json#L66) and [big int](https://github.com/ethereum/tests/blob/develop/RLPTests/rlptest.json#L154) were different because the number type was `String`.
Because of loss of precision of number, the encoded value were also different if number type was `Number`.
There was no further information In RLP wiki, so I post here.

Should rlp support bigint or mediumint in ethereum/tests?
Thanks!

**Comment by holgerd77** [comment]
Hi @sc0Vu, I am not really getting through this: would you like to suggest that ``ethereum/tests`` (which is the generic testing suite for different clients and implementations) includes RLP tests for big int numbers?

Or is your issue that this library should better support big int values in its implementation?

**Comment by holgerd77** [comment]
No further communication on this issue, will close.
