### ISSUE TITLE
Move from Travis to Circleci

### ISSUE THREAD

**Issue by axic** [ethereumjs/rlp#30]

**Comment by whymarrh** [comment]
Is this still something we're interested in? I can switch this over if it is.

**Comment by holgerd77** [comment]
We have seen large speed improvements on the VM CI runs on the switch. However here CI runs are not that long, from my personal perspective this has not that super-high priority. But if you see larger benefits on switching I wouldn't hold you back here.

**Comment by holgerd77** [comment]
Will close this for now, seems there is no imminent demand.
