### ISSUE TITLE
Analyze new listofbinaries RLP test case

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/rlp#47]
Running a new test in discussion on the tests (see https://github.com/ethereum/tests/pull/554 respectively https://github.com/ethereum/tests/pull/562) repo fails, it should be analyzed why.

**Comment by ryanio** [comment]
It seems that the test was never resolved to pass in aleth https://github.com/ethereum/tests/pull/562 and https://github.com/ethereum/tests/pull/562#issuecomment-515420350 and was closed as expired
