### ISSUE TITLE
Missing type exports: RLPInput, RLPDecoded

### ISSUE THREAD

**Issue by webmaster128** [ethereumjs/rlp#58]
The types `RLPInput`, `RLPDecoded` cannot be used in caller code because the index.d.ts does not export them.

A workaround is

```ts
// tslint:disable-next-line:no-submodule-imports
import { RLPInput } from "rlp/dist/types";
```

Having the types available is needed when you want to build a wrapper in TS like

```ts
export function toRlp(data: RLPInput): Uint8Array {
  const dataBuffer = rlp.encode(data);
  return Uint8Array.from(dataBuffer);
}
```

**Comment by holgerd77** [comment]
//cc @krzkaczor Can you have a look?

**Comment by holgerd77** [comment]
Not sure, do we want to expose these?

@webmaster128 TBH I find this use case not super convincing, do you really need a wrapper for this one extra call?

**Comment by webmaster128** [comment]
@holgerd77 Yes I do in order to consistently use Uint8Array for my binary data.

But the more interesting question is: should you export function without exporting its argument or return types? Looks like to is possible but this approach is not convincing in my eyes.

**Comment by webmaster128** [comment]
By the way, unprefixing them would be nice to allow consistency when importing

```ts
import * as rlp from "rlp";

// use rlp.encode, rlp.encode, rlp.Input, rlp.Decoded
```

**Comment by holgerd77** [comment]
I'll wait for the answers from @krzkaczor, he is the ``TypeScript`` expert! 😄

**Comment by holgerd77** [comment]
I actually think it make sense what you propose on a second thought - also the unprefixing. If you would manage to do a short-term PR on this I would merge and can probably directly release tomorrow along a necessary bugfix release planned.

**Comment by krzkaczor** [comment]
I agree that exporting these types is a good idea @webmaster128 @holgerd77. Btw. It's great that we already have some typescript users ❤️ 

I think we should simply add `export * from "./types";` in `index.ts`.
