### ISSUE TITLE
Cannot find module 'bn.js' error when requiring after clean install

### ISSUE THREAD

**Issue by tinchoabbate** [ethereumjs/rlp#63]
To reproduce:
1) Run `npm init -y` and `npm install rlp`
2) In that directory, run `node` and try to import `rlp` module with `require('rlp')`
3) Following error appears:
~~~bash
$ node
> require('rlp')
Error: Cannot find module 'bn.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
>
~~~

This is probably due to `bn.js` listed as a devDependency in package.json, instead of as a regular dependency. Moving `bn.js` to dependencies should fix this error.

**Comment by holgerd77** [comment]
Fixed by [v2.2.0](https://github.com/ethereumjs/rlp/releases/tag/v2.2.2) release.
