### ISSUE TITLE
Encoding and Decoding RLP lists when part of a buffer

### ISSUE THREAD

**Issue by Mikerah** [ethereumjs/rlp#77]
I am encountering a problem in which I try to RLP decode some data that was a part of a larger buffer. Here's an example to illustrate
```{js}
let buf1 = Buffer.from('a')
let buf2 = RLP.encode([1, 2, 3])
let buf3 = Buffer.from('b')
let final_buf = Buffer.concat([buf1, buf2, buf3])

// Slicing
let letter_a = final_buf.slice(0,1)
let rlp_list = final_buf.slice(1,4)
let letter_b = final_buf.slice(4,5)

// Error occurs when trying to index the decoded rlp_list.
// rlp_list[i] is a number instead of an array element since rlp_list,
// upon being decoded is a buffer and not an array of buffers.
rlp_list = RLP.decode(rlp_list)
```

I am using typescript but the above example applies. How do I remedy this?

**Comment by s1na** [comment]
RLP prepends meta-data to the Buffer. E.g. in your code snippet, the correct way to slice it would be:

```js
let final_buf = Buffer.concat([buf1, buf2, buf3])

console.log(final_buf)
// Note the "c3" before the items
// <Buffer 61 c3 01 02 03 62>

let rlp_list = final_buf.slice(1,5)
let letter_b = final_buf.slice(5,6)
```

Could it be that you're not decoding the complete RLP-serialized buffer?

**Comment by Mikerah** [comment]
I have amended my code to slice as you say. I'm still getting the same issue I described earlier. The typescript compiler seems like it can't tell the difference at compile-time which is odd because I looked through the RLP code in this repo and it takes into account lists.

**Comment by s1na** [comment]
Ah if it's a compile-time typescript error I might have an idea why. This is the type definitions for `decode`:

https://github.com/ethereumjs/rlp/blob/f06a96fa061127d8b85c45bd1dfae1b067426c0f/src/index.ts#L60-L63

`Buffer.slice` returns a Buffer, which means the first definition is taken and the result is assumed to be a `Buffer`, which is why you can't index it.

Can you try something like this:

```typescript
import { Input } from 'rlp'
rlp_list: Buffer[] = RLP.decode(rlp_list as Input)
```

I've faced similar issues with `decode`'s type definitions before. I think we might need to improve on that.

**Comment by Mikerah** [comment]
I tried the above and it compiles! Thank you very much for your help!
Temporarily, it would make sense to have more extensive documentation about this. However, as `Input` is indeed an internal implementation detail it would make sense to fix it outright.

**Comment by holgerd77** [comment]
@s1na Can you open an issue so that this won't get lost?
