### ISSUE TITLE
Improve type definitions for decode

### ISSUE THREAD

**Issue by s1na** [ethereumjs/rlp#78]
Thinking abstractly about `decode` I'd expect a function signature such as:

```typescript
export function decode(input: Buffer): NestedBufferList
```

where `NestedBufferList` could be any nested composition of buffers and arrays such as `Buffer`, or `Buffer[]`, or `[Buffer, Buffer[]]`, etc. (haven't tried expressing this in TS).

Currently the `decode` method has the following definitions:

https://github.com/ethereumjs/rlp/blob/f06a96fa061127d8b85c45bd1dfae1b067426c0f/src/index.ts#L60-L63

1. First definition takes `Buffer` and returns a `Buffer`. Not sure why, it could very well be that the decoding is a `NestedBufferList`. This was also the problem stated in #77
2. Second def. takes a `Buffer[]`. Is this to support decoding multiple serialized items simultaneously? the code doesn't seem to do that. I suggest we remove this
3. The last two take `Input` as argument. I imagine this is for backwards-compatibility. I suggest we tighten the API and only accept a `Buffer`

On the `stream` flag: we could keep it, or add a new function `decodeStreaming`.

**Comment by wemeetagain** [comment]
An additional wrinkle, the readme says :
`rlp.decode(encoded, [skipRemainderCheck=false])` - Decodes an RLP encoded `Buffer`, `Array` or `String` and returns a `Buffer` or an `Array` of `Buffers`. If `skipRemainderCheck` is enabled, `rlp` will just decode the first rlp sequence in the buffer. By default, it would throw an error if there are more bytes in Buffer than used by rlp sequence.

It looks like the skipRemainderCheck logic is gone.
