### ISSUE TITLE
Handle negative numbers

### ISSUE THREAD

**Issue by mtsalenc** [ethereumjs/rlp#81]
Encoding BN instances of negative numbers just doesn't work, it seems to just convert them to unsigned integers.

Any way to get around this? perhaps we can do something similar to solidity int256.

**Comment by s1na** [comment]
[RLP](https://github.com/ethereum/wiki/wiki/RLP) doesn't really understand numbers, just byte arrays and lists. Internally this library converts numbers, BN and strings to Buffer before encoding them.

Try converting your number to a suitable byte representation (e.g. two's complement) and pass in the Buffer to avoid the encoder automatically converting it.

**Comment by mtsalenc** [comment]
I see, I thought it would do it out of the box.
Use two's complement as you suggested worked like a charm. Thanks a lot :+1:
